version: '3.9'

services:
  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
    volumes:
      - ./database:/var/lib/mysql
    restart: always
    command:
      [
        '--character-set-server=${WORDPRESS_DB_CHARSET}',
        '--collation-server=${WORDPRESS_DB_COLLATE}',
      ]

  wordpress:
    image: wordpress
    links:
      - mariadb:mysql
    depends_on:
      - mariadb
    environment:
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_CHARSET: ${WORDPRESS_DB_CHARSET}
      WORDPRESS_DB_COLLATE: ${WORDPRESS_DB_COLLATE}
    ports:
      - '8000:80'
    volumes:
      - ./html:/var/www/html
    restart: always
